language: c
env:
  matrix:
  - COMPILER=gcc TEST=integration
  - COMPILER=clang TEST=integration
  - COMPILER=gcc TEST=coverage
  - COMPILER=gcc TEST=install
  - COMPILER=gcc TEST=doc
script:
- tools/travis/run-script.sh
before_install:
- tools/travis/before-install.sh
install:
- tools/travis/install.sh
after_success:
- tools/travis/success.sh
notifications:
  email:
    recipients:
      - "%{author}@gmail.com"
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#%{author}"
    on_success: always
    on_failure: always

