language: c
env:
  matrix:
  - COMPILER=gcc TEST=integration
  - COMPILER=clang TEST=integration
  - COMPILER=gcc TEST=coverage
  - COMPILER=gcc TEST=install
script:
- tools/travis/run-script.sh
before_install:
- tools/travis/before-install.sh
install:
- tools/travis/install.sh
after_success:
- tools/travis/success.sh
